---
title: "Viz_part_02"
author: "Matthew Ma"
output: github_document
---

## Lets import data

```{r}
library(tidyverse)
```

This code from the the visualization module

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## `group_by()`

```{r}
weather_df %>% 
  group_by(month, name)
```

## `summarize()`

lets group and then summarize

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n()
  )
```

can we count in other ways?

```{r}

weather_df %>% 
  count(name, month)

```

Don't do tables

```{r, eval=FALSE}

weather_df %>% 
  pull(month) %>% 
  table()
```

you can have multiple summaries

```{r}

weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_dist = n_distinct(date)
  )
```

## a brief assign on 2x2 tables

```{r}

weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(
    n_obs = n()
  ) %>% 
  pivot_wider(
    names_from = cold,
    values_from = n_obs
  )

```

another way to use 2x2 table using janitor package.

```{r}

weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>%
  janitor::tabyl(name, cold)
```

## General summaries

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp), 
    median_tmax = median(tmax, na.rm = TRUE)
  ) %>% view
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))

```

```{r}

weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_path()
```


```{r}

weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digit = 2)
## this is going to render somewhat nicely

```


## Grouped mutates

```{r}

weather_df %>% 
  group_by(name) %>% 
  mutate(mean_tmax = mean(tmax, na.rm = TRUE),
         centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()

```


lagged observations

```{r}

weather_df %>% 
  group_by(name) %>% 
  mutate(
    yesterday_tmax = lag(tmax),
    tmax_change = tmax -yesterday_tmax
  ) %>% 
  summarize(
    sd_tmax_change = sd(tmax_change, na.rm = TRUE)
  )
```

One other window function

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(
    tmax_rank = min_rank(tmax)
    #ranking the coldest days using min_rank, using desc( )on tmax for reverse order.
  ) %>% 
  filter(tmax_rank < 4) %>% 
  arrange(name, month, tmax_rank) %>% view
```


